### ISSUE TITLE
Unit advices

### ISSUE THREAD

**Issue by Grewer** [Solant/nodegui-stylesheet#1]
I saw this library in your project before, and the usage is very similar to that of RN, which makes me feel more accustomed, except for the `Unit` method.
After my local debugging, I can adjust `font-size` without` Unit`, so I would like to ask if you want to remove `Unit`, if possible I will give you a PR, otherwise I will create one Own library.

**Comment by Solant** [comment]
@Grewer 
so, regarding this one: when I tested it on my own, I wasn't able to change font size without actual units (px in my tests) on linux, and I spent some time trying to find whats the issue

I can check how it works across different OS, and if it works fine without units everywhere, I'll add `number` as a possible type argument

but the original idea is to make typesafe (thats why `units` method is required) stylesheet implementation with some sanity checks to ensure proper styling

**Comment by Grewer** [comment]
I think that judging by the key name is font-size, is it better to put the operation of `unit` in `create`?

**Comment by Solant** [comment]
@Grewer 
just checked this on Linux, units are required to change `font-size` on Linux:
![ezgif-5-5bbd09b41472](https://user-images.githubusercontent.com/5971578/74833864-6156d080-532b-11ea-8d7f-21d43826188b.gif)
to make sure that we have cross-platform support, I'll leave `units` function in place, so nobody will have to deal with platform-dependent functionality

I'll leave a link to this issue in the readme, so we'll track those inconsistencies (well, this whole project is created to track them). thanks a lot for macOS report

**Comment by Grewer** [comment]
I mean, all fontSize must be added with a unit such as px to provide a unified specification, isn't it better?
```
fontSize: '20px', // work

fontSize:20, // report ts error, need string

fontSize: '20', // not work
```

Of course, this is just my opinion, I think it will be more comfortable

**Comment by Grewer** [comment]
Or provide a global configuration item px or pt
```
fontSize: 20,
```
In `create`, convert 20 to 20px

**Comment by Solant** [comment]
there is also one tricky case with font size:
https://doc.qt.io/qt-5/stylesheet-reference.html
>The font size. In this version of Qt, only pt and px metrics are supported.

so to ensure that font-size is passed in only 2 possible units during compile time I did it with types instead of strings

hmm, maybe its good idea to fallback number to pixel units. I'll do some changes for this one

**Comment by Grewer** [comment]
Oh, OK
Then I create a library of my own. I can provide a global configuration item `px`or `pt`  in the way I want and then use it: `fontSize: 20`

**Comment by Solant** [comment]
@Grewer 
looks like we misunderstood each other :)
I'll make a change to treat
```
{ font-size: 20 }
```
as
```
{ font-size: units(20, 'px') }
```

so you'll be able to pass typesafe units and number, that will be treated like pixel units

**Comment by Solant** [comment]
Added pixels fallback in https://github.com/Solant/nodegui-stylesheet/pull/2 , already merged and published to npm

I'll close this issue as fixed, feel free to create new issues if you need something

**Comment by Grewer** [comment]
Basically achieve the effect I want
