### ISSUE TITLE
property problem

### ISSUE THREAD

**Issue by Grewer** [Solant/nodegui-stylesheet#3]
styles is missing a lot of properties, just want to tell you, but found another branch `missing-properties`
So here are the properties that I need to pay attention to after testing yesterday:
```
borderBottomLeftRadius
borderBottomRightRadius
borderTopLeftRadius
borderTopRightRadius
borderRadius
width
height

// Can work normally
```

```
flexDirection: 'row' | 'column',
justifyContent ?: 'flex-start' | 'flex-end' | 'center' | 'space-between' | 'space-around' | 'space-evenly';
alignItems ?: 'flex-start' | 'flex-end' | 'center' | 'stretch' | 'space-between' | 'space-around'
flexDirection ?: 'row' | 'column' | 'row-reverse' | 'column-reverse';

// 'space-between' | 'space-around' of alignItems  I'm not sure
```

```
border string
<Text style = {`border: 1px solid # 000;`}> test </ Text> It work

// There are also some problems with using borders directly.You need to use your toString function to return `border: 1px solid # 000;` instead of `border:" 1px solid # 000; "`
```

```
overflow: visible; // not work
opacity: 0.1 // not work
```

Hope you can post a new version to tell me after the properties are completed

**Comment by Grewer** [comment]
Another serious problem is that when the css layout changes, such as:
When `flexDirection: 'row'` becomes `flexDirection: 'column',`
With hot, the style will not change after the page is re-rendered, but the style will only change after I run `npm start` again

**Comment by Solant** [comment]
Hi
yep, working on adding new properties
> overflow: visible; // not work

qt css implementation doesn't support this property, so you should resolve it using qscrollarea widget

>opacity: 0.1 // not work

same here, qt css implementation is different from css3: `opacity` value should be **number between 0 and 255**, and it **works only on tooltips**

**Comment by Solant** [comment]
added all supported qt properties, excluding some alias ones, due to issues with type safety

feel free to open an issue if some yoga flexbox props are missing, or something doesn't work as expected
